spotlight: key("cmd-space")
tack all full: key("cmd-ctrl-f")
tack full: key("cmd-alt-f")
tack left: key("cmd-alt-left")
tack right: key("cmd-alt-right")
tack upper left: key("ctrl-cmd-left")
tack upper right: key("ctrl-cmd-right")
tack lower left: key("ctrl-shift-cmd-left")
tack lower right: key("ctrl-shift-cmd-right")
tack move left: key("ctrl-cmd-alt-left")
tack move right: key("ctrl-cmd-alt-right")
tack up: key("cmd-alt-up")
tack down: key("cmd-alt-down")
you are: key("alt-space")
